title = "Dustin Miller's weblog"
description = "A simple link blog"
base_url = "https://dustinmiller.win"

generate_feeds = true

taxonomies = [
    { name = "tags", feed = true },
]

[extra]
author = "Dustin Miller"
